// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BmwdisplayV1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BACKGROUND;
lv_obj_t * ui_IMGCoolant;
lv_obj_t * ui_IMGTemp;
lv_obj_t * ui_IMGTemp1;
lv_obj_t * ui_IMGSpeed;
lv_obj_t * ui_SPEED;
lv_obj_t * ui_IMGRpm;
lv_obj_t * ui_RPM;
lv_obj_t * ui_Label4;
lv_obj_t * ui_INn;
lv_obj_t * ui_OUT;
lv_obj_t * ui_TEMPIN;
lv_obj_t * ui_TEMPOUT;
lv_obj_t * ui_COOLANTTEMP;
lv_obj_t * ui_TempCool;
void ui_event_NEXTButton(lv_event_t * e);
lv_obj_t * ui_NEXTButton;
// CUSTOM VARIABLES
lv_obj_t * uic_SPEED;
lv_obj_t * uic_RPM;
lv_obj_t * uic_TEMPIN;
lv_obj_t * uic_TEMPOUT;
lv_obj_t * uic_COOLANTTEMP;
lv_obj_t * uic_TempCool;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_PREVButton(lv_event_t * e);
lv_obj_t * ui_PREVButton;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_next[1] = {&ui_img_next1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_NEXTButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_PREVButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
