// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BmwdisplayV1

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PREVButton = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_PREVButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_prev_png, NULL);
    lv_obj_set_height(ui_PREVButton, 64);
    lv_obj_set_width(ui_PREVButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PREVButton, -133);
    lv_obj_set_y(ui_PREVButton, 5);
    lv_obj_set_align(ui_PREVButton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_PREVButton, ui_event_PREVButton, LV_EVENT_ALL, NULL);

}
