// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BmwdisplayV1

#ifndef _BMWDISPLAYV1_UI_H
#define _BMWDISPLAYV1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BACKGROUND;
extern lv_obj_t * ui_IMGCoolant;
extern lv_obj_t * ui_IMGTemp;
extern lv_obj_t * ui_IMGTemp1;
extern lv_obj_t * ui_IMGSpeed;
extern lv_obj_t * ui_SPEED;
extern lv_obj_t * ui_IMGRpm;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_INn;
extern lv_obj_t * ui_OUT;
extern lv_obj_t * ui_TEMPIN;
extern lv_obj_t * ui_TEMPOUT;
extern lv_obj_t * ui_COOLANTTEMP;
extern lv_obj_t * ui_TempCool;
void ui_event_NEXTButton(lv_event_t * e);
extern lv_obj_t * ui_NEXTButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SPEED;
extern lv_obj_t * uic_RPM;
extern lv_obj_t * uic_TEMPIN;
extern lv_obj_t * uic_TEMPOUT;
extern lv_obj_t * uic_COOLANTTEMP;
extern lv_obj_t * uic_TempCool;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_PREVButton(lv_event_t * e);
extern lv_obj_t * ui_PREVButton;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_coolant_png);    // assets/coolant.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/Temp.png
LV_IMG_DECLARE(ui_img_speed_png);    // assets/speed.png
LV_IMG_DECLARE(ui_img_rpm_png);    // assets/RPM.png
LV_IMG_DECLARE(ui_img_next1_png);    // assets/next1.png
LV_IMG_DECLARE(ui_img_prev_png);    // assets/prev.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
