// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BmwdisplayV1

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BACKGROUND = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BACKGROUND, 352);
    lv_obj_set_height(ui_BACKGROUND, 265);
    lv_obj_set_x(ui_BACKGROUND, 2);
    lv_obj_set_y(ui_BACKGROUND, -2);
    lv_obj_set_align(ui_BACKGROUND, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BACKGROUND, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACKGROUND, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACKGROUND, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMGCoolant = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_IMGCoolant, &ui_img_coolant_png);
    lv_obj_set_width(ui_IMGCoolant, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_IMGCoolant, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_IMGCoolant, -131);
    lv_obj_set_y(ui_IMGCoolant, 79);
    lv_obj_set_align(ui_IMGCoolant, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGCoolant, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMGCoolant, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IMGCoolant, 70);

    ui_IMGTemp = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_IMGTemp, &ui_img_temp_png);
    lv_obj_set_width(ui_IMGTemp, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_IMGTemp, LV_SIZE_CONTENT);    /// 208
    lv_obj_set_x(ui_IMGTemp, -132);
    lv_obj_set_y(ui_IMGTemp, 14);
    lv_obj_set_align(ui_IMGTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMGTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IMGTemp, 60);

    ui_IMGTemp1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_IMGTemp1, &ui_img_temp_png);
    lv_obj_set_width(ui_IMGTemp1, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_IMGTemp1, LV_SIZE_CONTENT);    /// 208
    lv_obj_set_x(ui_IMGTemp1, -2);
    lv_obj_set_y(ui_IMGTemp1, 15);
    lv_obj_set_align(ui_IMGTemp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGTemp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMGTemp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IMGTemp1, 60);

    ui_IMGSpeed = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_IMGSpeed, &ui_img_speed_png);
    lv_obj_set_width(ui_IMGSpeed, LV_SIZE_CONTENT);   /// 358
    lv_obj_set_height(ui_IMGSpeed, LV_SIZE_CONTENT);    /// 337
    lv_obj_set_x(ui_IMGSpeed, -130);
    lv_obj_set_y(ui_IMGSpeed, -53);
    lv_obj_set_align(ui_IMGSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMGSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IMGSpeed, 35);

    ui_SPEED = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SPEED, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_SPEED, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_SPEED, -67);
    lv_obj_set_y(ui_SPEED, -53);
    lv_obj_set_align(ui_SPEED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPEED, "%S%");
    lv_obj_set_style_text_font(ui_SPEED, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMGRpm = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_IMGRpm, &ui_img_rpm_png);
    lv_obj_set_width(ui_IMGRpm, LV_SIZE_CONTENT);   /// 279
    lv_obj_set_height(ui_IMGRpm, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_x(ui_IMGRpm, 25);
    lv_obj_set_y(ui_IMGRpm, -56);
    lv_obj_set_align(ui_IMGRpm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMGRpm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMGRpm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IMGRpm, 45);

    ui_RPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM, 102);
    lv_obj_set_y(ui_RPM, -56);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM, "%RPM");
    lv_obj_set_style_text_font(ui_RPM, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 5);
    lv_obj_set_y(ui_Label4, -94);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SPEED                  RPM");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_INn = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_INn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_INn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_INn, -110);
    lv_obj_set_y(ui_INn, 29);
    lv_obj_set_align(ui_INn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_INn, "IN");
    lv_obj_set_style_text_font(ui_INn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OUT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OUT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OUT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OUT, 28);
    lv_obj_set_y(ui_OUT, 30);
    lv_obj_set_align(ui_OUT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OUT, "OUT");
    lv_obj_set_style_text_font(ui_OUT, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPIN = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEMPIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPIN, -81);
    lv_obj_set_y(ui_TEMPIN, 7);
    lv_obj_set_align(ui_TEMPIN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPIN, "%TEM");
    lv_obj_set_style_text_font(ui_TEMPIN, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TEMPOUT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TEMPOUT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TEMPOUT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TEMPOUT, 51);
    lv_obj_set_y(ui_TEMPOUT, 7);
    lv_obj_set_align(ui_TEMPOUT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TEMPOUT, "%TEM");
    lv_obj_set_style_text_font(ui_TEMPOUT, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_COOLANTTEMP = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_COOLANTTEMP, 10, 140);
    lv_bar_set_value(ui_COOLANTTEMP, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_COOLANTTEMP, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_COOLANTTEMP, 177);
    lv_obj_set_height(ui_COOLANTTEMP, 30);
    lv_obj_set_x(ui_COOLANTTEMP, -13);
    lv_obj_set_y(ui_COOLANTTEMP, 83);
    lv_obj_set_align(ui_COOLANTTEMP, LV_ALIGN_CENTER);

    ui_TempCool = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempCool, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_TempCool, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_TempCool, 113);
    lv_obj_set_y(ui_TempCool, 81);
    lv_obj_set_align(ui_TempCool, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCool, "%CT");
    lv_obj_set_style_text_font(ui_TempCool, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NEXTButton = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_NEXTButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next1_png, NULL);
    lv_obj_set_height(ui_NEXTButton, 67);
    lv_obj_set_width(ui_NEXTButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_NEXTButton, 133);
    lv_obj_set_y(ui_NEXTButton, 7);
    lv_obj_set_align(ui_NEXTButton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_NEXTButton, ui_event_NEXTButton, LV_EVENT_ALL, NULL);
    uic_SPEED = ui_SPEED;
    uic_RPM = ui_RPM;
    uic_TEMPIN = ui_TEMPIN;
    uic_TEMPOUT = ui_TEMPOUT;
    uic_COOLANTTEMP = ui_COOLANTTEMP;
    uic_TempCool = ui_TempCool;

}
